//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.AgendamentoConsulta = new HashSet<AgendamentoConsulta>();
        }
    
        public int ID_Cliente { get; set; }
        public string Nome { get; set; }
        public Nullable<int> Idade { get; set; }
        public string TipoIdade { get; set; }
        public string Sexo { get; set; }
        public string CNS { get; set; }
        public string Familia { get; set; }
        public string Prontuario { get; set; }
        public string Endereco { get; set; }
        public string Situacao { get; set; }
        public int ID_Unidade { get; set; }
    
        public virtual Unidade Unidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgendamentoConsulta> AgendamentoConsulta { get; set; }
    }
}
