//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int ID_Usuario { get; set; }
        public string CPF { get; set; }
        public string Nome { get; set; }
        public string Senha { get; set; }
        public Nullable<bool> Status_ { get; set; }
        public Nullable<bool> Acesso { get; set; }
    }
}
