//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAgendamentoConsulta
    {
        public int ID_AgendamentoConsulta { get; set; }
        public Nullable<System.DateTime> DataConsulta { get; set; }
        public Nullable<System.TimeSpan> HoraConsulta { get; set; }
        public Nullable<System.DateTime> DataAgendamento { get; set; }
        public string Prontuario { get; set; }
        public string Telefone { get; set; }
        public string Celular { get; set; }
        public string UnidadePrestadora { get; set; }
        public string NomeProfissional { get; set; }
        public string Especialidade { get; set; }
        public string Tipo { get; set; }
        public string Situacao { get; set; }
        public int ID_Cliente { get; set; }
        public string Nome { get; set; }
        public int ID_Unidade { get; set; }
        public string Descricao { get; set; }
    }
}
